application: gaeshakyo-with-go
version: 1
runtime: go
api_version: go1

handlers:
- url: /statics
  static_dir: statics
- url: /.*
  script: _go_app
- url: /tq/.*
  script: _go_app
  login: admin
- url: /cron/.*
  script: _go_app
  login: admin
- url: /auth/.*
  script: _go_app
  login: required
- url: /admin/.*
  script: _go_app
  login: admin

inbound_services:
  - mail
